name: flutter_date_range_picker
description: A Flutter package for all platform which provides a custom date picker
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  intl: ^0.19.0

  syncfusion_flutter_datepicker: ^26.1.40

  pattern_formatter: 4.0.0

  flutter_svg: ^2.0.9

  debounce_throttle: 2.0.0

  pointer_interceptor: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
